### ISSUE TITLE
Can't clone to non-shared storage

### ISSUE THREAD

**Issue by Intuinewin** [ionos-cloud/cluster-api-provider-proxmox#107]
Hi, I'm facing a proxmox issue and I'm wondering if a workaround could be implemented here to fix this behavior.

**What steps did you take and what happened:**

Context: I have a proxmox cluster with a shared storage(rbd) containing my template disk and I want to create a cluster on multiple nodes. I want to use nodes' local storage pool as it is faster than my ceph cluster.

The problem is:
If the storage destination is a non shared storage, I can only clone the template on the node where the template is located otherwise I get this error: "500 Can't clone to non-shared storage 'local-lvm'"

**What did you expect to happen:**

As the disk is shared, I would expect the clone to be successful

**Anything else you would like to add:**

A solution could be to do a linked clone of the template on the node and clone the vm from it. Then delete the linked clone.

cf: https://forum.proxmox.com/threads/500-cant-clone-to-non-shared-storage-local.49078/
cf: https://bugzilla.proxmox.com/show_bug.cgi?id=2059

**Environment:**

- Cluster-api-provider-proxmox version: 0.2.0
- Kubernetes version: (use `kubectl version`): 1.29.1
- OS (e.g. from `/etc/os-release`): Debian 12

**Comment by mcbenjemaa** [comment]
@Intuinewin 
Proxmox doesn't allow cloning of VMS to different nodes with local storage; that's a requirement.  
and we also support shared storage.


But you can maybe clone vms with local storage to the same proxmox node, so you need to use a single node to create your cluster.

**Comment by wikkyk** [comment]
As this is a limitation of Proxmox VE, it's not really something we can support so I'm closing this as invalid.
@Intuinewin if you disagree feel free to reopen :)
