### ISSUE TITLE
Full IPAM 0.1.0 and Go 1.21 support

### ISSUE THREAD

**Issue by wikkyk** [ionos-cloud/cluster-api-provider-proxmox#116]
As documented in a93bff1f0efb7efce4432b30e52d4fff8516ea12, IPAM 0.1.0 requires Go 1.21. Some of our tests aren't working with Go 1.21; however, we do know that we can work with IPAM 0.1.0 otherwise.

This is a blocker for 0.4.0.

**Comment by 65278** [comment]
I've successfully run ipam v0.1.0 with Cluster-API 1.6.2. Didn't try 1.6.1, but it should work (IPA v0.1.0 was released before Cluster-API v1.6.2).
