### ISSUE TITLE
Document IPv6 only clusters incomaptible with kube-vip < 0.7.2

### ISSUE THREAD

**Issue by 65278** [ionos-cloud/cluster-api-provider-proxmox#144]
**Describe the solution you'd like**
kube-vip tries to define the cluster interface by looking for the default route. For versions < v0.7.2, this does not work in IPv6 only environments because IPv6 routing tables are not considered:
```
root@ipv6test01-control-plane-5000b-mg75w:~# crictl logs d1dd2691d6aab
time="2024-03-14T11:48:58Z" level=info msg="Starting kube-vip.io [v0.5.10]"
time="2024-03-14T11:48:58Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[false]"
time="2024-03-14T11:48:58Z" level=info msg="No interface is specified for VIP in config, auto-detecting default Interface"
....
time="2024-03-14T11:52:30Z" level=fatal msg="unable to detect default interface -> [Unable to find default route]"
```
Document this (and the kube vip default interface template variable) for future releases.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-proxmox version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by wikkyk** [comment]
done #172
