### ISSUE TITLE
Crashloop Backoff capmox-controller-manager

### ISSUE THREAD

**Issue by mariusbertram** [ionos-cloud/cluster-api-provider-proxmox#155]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

After `clusterctl init --bootstrap talos --control-plane talos --infrastructure proxmox --ipam in-cluster`
the capmox-controller-manager can't setup the promos API Client 

```
I0326 00:40:45.030910       1 main.go:88] "starting capmox" logger="setup"
I0326 00:40:45.057362       1 main.go:122] "feature gates: ClusterTopology=false\n" logger="setup"
E0326 00:40:45.159914       1 main.go:129] "unable to setup proxmox API client" err="unable to initialize proxmox api client: 501 Method 'GET /api2/json/version' not implemented" logger="setup"
```

**What did you expect to happen:**
The container should be up and running.
With the same proxmox  node and the same credentials it work previously. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-proxmox version: 0.3.0
- Kubernetes version: (use `kubectl version`):
  Client Version: v1.29.3
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.29.2 - kind Cluster 
- OS (e.g. from `/etc/os-release`): 
  MacOS 14.4

**Comment by mcbenjemaa** [comment]
What is the version of your Proxmo host?

**Comment by mariusbertram** [comment]
My Host has Proxmox 8.1.5
If I do 
`clusterctl init --infrastructure proxmox --ipam in-cluster`
and then
`clusterctl init --bootstrap talos --control-plane talos --infrastructure proxmox --ipam in-cluster`

The Container doesn't have a problem.

**Comment by mcbenjemaa** [comment]
that's a network issue, or might be your Proxmox API not reliable.

**Comment by mariusbertram** [comment]
Now it´s working. I will close the issue.
