### ISSUE TITLE
Support for linked clones

### ISSUE THREAD

**Issue by cfredericksen** [ionos-cloud/cluster-api-provider-proxmox#174]
**What steps did you take and what happened:**
Set "full: false", "format: qcow" or "format: raw"...also tried to not set format. Backend storage is NFS.
```
I0412 17:22:22.707171       1 recorder.go:104] "events: failed to sync MachineSet replicas: failed to clone infrastructure machine from ProxmoxMachineTemplate qa-worker while creating a machine: ProxmoxMachine.infrastructure.cluster.x-k8s.io \"qa-worker-72zf9\" is invalid: spec: Invalid value: \"object\": Must set full=true when specifying format" type="Warning" object={"kind":"MachineSet","namespace":"default","name":"qa-workers-gh8gs","uid":"8451b7f1-f5be-4505-a0c6-13bf0ac175db","apiVersion":"cluster.x-k8s.io/v1beta1","resourceVersion":"444395"} reason="ReconcileError"
```

**What did you expect to happen:**
A linked clone would be created

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Maybe I am an idiot but I couldnt find anything in the docs to enable linked clones. 

**Environment:**

- Cluster-api-provider-proxmox version: 0.3.0
- Kubernetes version: (use `kubectl version`): 1.28.7
- OS (e.g. from `/etc/os-release`):  Ubuntu 22.04 from image-builder

**Comment by wikkyk** [comment]
From your log,
>Must set full=true when specifying format
We do not currently support this.
