### ISSUE TITLE
Default gateway creation

### ISSUE THREAD

**Issue by wikkyk** [ionos-cloud/cluster-api-provider-proxmox#182]
From @65278:

At the moment, we try to create a default gateway for every interface.
That only works by accident and netplan can stop working any time.

**Comment by 65278** [comment]
Unorganized thoughts:
1. I've introduced metrics to routes in 0.4.0, so the default interface route never conflicts with other routes, so netplan can no longer fail on randomly changing the order of interfaces here ... but all extra interface routes get the same metric, so if it starts erroring, it'll still fail.
2. `getNetworkConfigDataForDevice` always sets a gateway. An cluster-api-provider-in-cluster-ipam object can never not have a gateway. This needs to be patched upstream.
3. Perhaps we don't want to use the gateway of IPAM unless we're at the default device. For all further interfaces we can set routes using the newly introduced routing templating from 0.4.0. That way we don't need to change upstream. This is not my preferred solution.
