### ISSUE TITLE
bump go to 1.22

### ISSUE THREAD

**Issue by wikkyk** [ionos-cloud/cluster-api-provider-proxmox#187]
Needed by #183 ~#186~

https://github.com/ionos-cloud/cluster-api-provider-proxmox/labels/go1.22

**Comment by SimonKienzler** [comment]
Hi 👋🏻 I just tried to set up development on the current `main` and had problems running `make generate` using go `1.22.1`. `controller-gen` panics in version `v0.11.3` when used with this version of go. See https://github.com/kubernetes-sigs/controller-tools/issues/880 

Bumping to `v0.14.0` solved the issue for me.

**Comment by wikkyk** [comment]
@SimonKienzler we're aware but thanks for reminding me :)

**Comment by wikkyk** [comment]
postponed until v0.6.

**Comment by wikkyk** [comment]
https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/releases/release-1.8.md
It's likely we'll need to postpone it until CAPI 1.8.

**Comment by wikkyk** [comment]
https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.8.0
capi 1.8.0 released with support for go 1.22
