### ISSUE TITLE
(question) does horizontal pod autoscaling work with this provider?

### ISSUE THREAD

**Issue by lknite** [ionos-cloud/cluster-api-provider-proxmox#294]
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

**Comment by mcbenjemaa** [comment]
Yes, it should work.
but you need to deploy a metrics-server that can expose metrics to the controller manager.

if you require to customize it you will need to add more options in the controller-manager.

**Comment by lknite** [comment]
ok, getting close to being able to test.  Thank you.
