### ISSUE TITLE
BUG: provider-id should be opt-in

### ISSUE THREAD

**Issue by pborn-ionos** [ionos-cloud/cluster-api-provider-proxmox#345]
With #292 a breaking change was introduced, which forces `provider-id: proxmox://{{ .InstanceID }}` through cloud-init: https://github.com/ionos-cloud/cluster-api-provider-proxmox/blob/51a9d0a454937e3a12f74cbdf287afe10756e1b7/pkg/cloudinit/metadata.go#L23C1-L23C12

This will break any setup, that requires a `providerID` in a different format than set by CAPMOX, and it can't be altered by a third party CCM/automation either, since `Node.spec.providerID` is an immutable field:
```
$ k patch node dev-node-f56ef5 -p '{"spec":{"providerID":"foo"}}'
The Node "dev-node-f56ef5" is invalid: spec.providerID: Forbidden: node updates may not change providerID except from "" to valid
```

Slightly related to #342.

**Comment by wikkyk** [comment]
ref https://github.com/ionos-cloud/cluster-api-provider-proxmox/pull/292

Potentially breaks:
https://github.com/sergelogvinov/proxmox-cloud-controller-manager 
https://github.com/sergelogvinov/proxmox-csi-plugin

**Comment by mcbenjemaa** [comment]
Why don't you use a cluster template that doesn't include the provider ID? 
https://github.com/ionos-cloud/cluster-api-provider-proxmox/blob/main/templates/cluster-template.yaml#L158

**Comment by mcbenjemaa** [comment]
However, that was added for Talos.
https://github.com/ionos-cloud/cluster-api-provider-proxmox/blob/51a9d0a454937e3a12f74cbdf287afe10756e1b7/pkg/cloudinit/metadata.go#L23
