### ISSUE TITLE
Non-standard bootstrap secret breaks reconciliation

### ISSUE THREAD

**Issue by codecae** [ionos-cloud/cluster-api-provider-proxmox#353]
A change has been introduced in 0.6.0 that violates the Cluster API standard for bootstrap secrets:

https://github.com/ionos-cloud/cluster-api-provider-proxmox/blob/8b892ad6b6ba12db00a771bf338f1ce7cfffa850/internal/service/vmservice/bootstrap.go#L161-L164

An additional secret key named 'format' does not adhere to the standard and breaks compatibility with many bootstrap providers in the cluster api bootstrap provider list. 

https://cluster-api.sigs.k8s.io/developer/providers/bootstrap#bootstrap-secret

**Comment by mcbenjemaa** [comment]
It's already solved with v0.6.1

**Comment by codecae** [comment]
Thank you for the prompt response!
