### ISSUE TITLE
Release v0.2.0

### ISSUE THREAD

**Issue by mcbenjemaa** [ionos-cloud/cluster-api-provider-proxmox#70]
## Release

Release v0.2.0

## Checklist

- [x] Update metadata & clusterctl-settings
- [x] Update docs, (compatibility table, usage etc) .
- [x] create Tag.
- [x] update the created draft release to include (BREAKING Changes, Important Notes).
- [x] Publish the release.
- [ ] OPTIONAL: create release branch.

**Comment by wikkyk** [comment]
https://github.com/ionos-cloud/cluster-api-provider-proxmox/releases/tag/v0.2.0
