### ISSUE TITLE
BUG: unable to initialize proxmox api client not authorized to access endpoint

### ISSUE THREAD

**Issue by dnviti** [ionos-cloud/cluster-api-provider-proxmox#86]
**What steps did you take and what happened:**
After installing all prerequisites and running the command
```bash
clusterctl init --infrastructure proxmox --ipam in-cluster --core cluster-api:v1.5.3
```
when watching pods creating i notice that the capmox-controller is in CrashLoopback.
Pod Logs:
```
I0124 23:54:17.007521       1 main.go:87] "setup: starting capmox"
I0124 23:54:17.008105       1 listener.go:44] "controller-runtime/metrics: Metrics server is starting to listen" addr="localhost:8080"
I0124 23:54:17.008556       1 main.go:126] "setup: feature gates: ClusterTopology=false\n"
E0124 23:54:20.031775       1 main.go:133] "setup: unable to setup proxmox API client" err="unable to initialize proxmox api client: not authorized to access endpoint"
```

clusterctl.yaml
```yaml
PROXMOX_URL: "https://pve.dev.local/api2/json"
PROXMOX_TOKEN: "capi@pve!token1"
PROXMOX_SECRET: "REDACTED"
PROXMOX_SOURCENODE: "pve01"
TEMPLATE_VMID: "9000"
ALLOWED_NODES: "[pve01,pve02,pve03]"
VM_SSH_KEYS: "ssh-rsa ..."
CONTROL_PLANE_ENDPOINT_IP: "192.168.254.40"
NODE_IP_RANGES: "[192.168.254.50-192.168.254.80]"
GATEWAY: "192.168.254.1"
IP_PREFIX: "24"
DNS_SERVERS: "[192.168.254.1]"
BRIDGE: "vmbr0"
BOOT_VOLUME_DEVICE: "scsi0"
BOOT_VOLUME_SIZE: "64"
NUM_SOCKETS: "1"
NUM_CORES: "4"
MEMORY_MIB: "4096"
EXP_CLUSTER_RESOURCE_SET: "false"
CONTROL_PLANE_MACHINE_COUNT: "3"
WORKER_MACHINE_COUNT: "3"

providers:
  - name: in-cluster
    url: https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/releases/latest/ipam-components.yaml
    type: IPAMProvider
```

capi@pve!token1 is proxmox Administrator on / so it's cluster admin.
Yesyed the user on terraform and packer and ansible and everything works fine there.

**What did you expect to happen:**
The capmox-controller should connect to proxmox and continue provisioning

**Anything else you would like to add:**
Using kind as local kubernetes provisioner and docker rootless as driver, everything it at default configuration.

**Environment:**

- Cluster-api-provider-proxmox version: 0.1.1
- Kubernetes version: (use `kubectl version`):
```
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
- OS (e.g. from `/etc/os-release`):
```
NAME="AlmaLinux"
VERSION="9.3 (Shamrock Pampas Cat)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.3 (Shamrock Pampas Cat)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.3"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"
```

It's systematic so i must be doing something wrong...

**Comment by mcbenjemaa** [comment]
@dnviti 
the `PROXMOX_URL: "https://pve.dev.local/api2/json"` is wrong,

Please just use `PROXMOX_URL: "https://pve.dev.local"`

**Comment by dnviti** [comment]
It didn't work either way.

BTW this morning it gives me the error:
```
[default@capi-bootstrapper ~]$ clusterctl init --infrastructure proxmox --ipam in-cluster --core cluster-api:v1.5.3
Fetching providers
Error: failed to get provider components for the "proxmox" provider: failed to get repository client for the InfrastructureProvider with name proxmox: error creating the GitHub repository client: failed to get latest release: release not found for version v0.2.0, please retry later or set "GOPROXY=off" to get the current stable release: 404 Not Found
```

if i only run `clusterctl init` it works but it does not initialize the proxmox provider.

**Comment by mcbenjemaa** [comment]
yeah, we are currently releasing v0.2.0.

you can enforece the version by

```
clusterctl init --infrastructure proxmox:v0.1.1 --ipam in-cluster --core cluster-api:v1.5.3
Fetching providers
```

**Comment by dnviti** [comment]
> yeah, we are currently releasing v0.2.0.
> 
> you can enforce the version by
> 
> ```
> clusterctl init --infrastructure proxmox:v0.1.1 --ipam in-cluster --core cluster-api:v1.5.3
> Fetching providers
> ```

Nope, not working either, i'm going to wait for the v0.2.0 and try again.
Anyway, where can i check available providers/infrastructures? can't find the list anywhere...

**Comment by mcbenjemaa** [comment]
please retry or put this in your clusterctl

```
providers:
  - name: proxmox
    url: https://github.com/ionos-cloud/cluster-api-provider-proxmox/releases/download/v0.1.1/infrastructure-components.yaml
    type: InfrastructureProvider

```

**Comment by dnviti** [comment]
It starts but gives the same error 
```
I0124 23:54:17.007521       1 main.go:87] "setup: starting capmox"
I0124 23:54:17.008105       1 listener.go:44] "controller-runtime/metrics: Metrics server is starting to listen" addr="localhost:8080"
I0124 23:54:17.008556       1 main.go:126] "setup: feature gates: ClusterTopology=false\n"
E0124 23:54:20.031775       1 main.go:133] "setup: unable to setup proxmox API client" err="unable to initialize proxmox api client: not authorized to access endpoint"
```

Can't really figure out why, i strictly followed documentation steps.

**Comment by dnviti** [comment]
> @dnviti Do you think the token is correct?
> 
> OR maybe you should add the port PROXMOX_URL: "https://pve.dev.local:8006"

nope that, my access is granted and managed by an HAProxy so i use another domain, that was a random example

**Comment by mcbenjemaa** [comment]
I think I remember this issue:

Please disable privilege separation or use root token,

![Screenshot 2024-01-25 at 15 33 50](https://github.com/ionos-cloud/cluster-api-provider-proxmox/assets/15221272/d3860cd3-206f-4cb8-b8b5-84098f5055e0)

**Comment by dnviti** [comment]
> I think I remember this issue:
> 
> Please disable privilege separation or use root token,
> 
> ![Screenshot 2024-01-25 at 15 33 50](https://private-user-images.githubusercontent.com/15221272/299700306-d3860cd3-206f-4cb8-b8b5-84098f5055e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTM2MTgsIm5iZiI6MTcwNjE5MzMxOCwicGF0aCI6Ii8xNTIyMTI3Mi8yOTk3MDAzMDYtZDM4NjBjZDMtMjA2Zi00Y2I4LWI4YjUtODQwOThmNTA1NWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE0MzUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZWMyM2EzZWFiMDg0YWQ2NjhjYjY2MTJmMGI2MmU2ODc5ODdjZDhiN2VmZWRkMmYxYjY4OWEyYjEyMDkzNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nwq-XHC9FB6A8Uw2A1a_CAEwhdt-PVomoxy4B2hy_iI)

yes, i disabled previously "Privilege Separation" also on the other user and it worked using ansible.

Now all started and that is the log.
```
NAME                                                                   READY  SEVERITY  REASON                       SINCE  MESSAGE
Cluster/proxmox-quickstart                                             False  Warning   ScalingUp                    4m16s  Scaling up control plane to 3 replicas (actual 1)
├─ClusterInfrastructure - ProxmoxCluster/proxmox-quickstart            True                                          4m24s
├─ControlPlane - KubeadmControlPlane/proxmox-quickstart-control-plane  False  Warning   ScalingUp                    4m16s  Scaling up control plane to 3 replicas (actual 1)
│ └─Machine/proxmox-quickstart-control-plane-xhdfp                     False  Warning   CloningFailed                4m21s  1 of 2 completed
└─Workers
  └─MachineDeployment/proxmox-quickstart-workers                       False  Warning   WaitingForAvailableMachines  4m24s  Minimum availability requires 3 replicas, current 0 available
    └─3 Machines...                                                    False  Info      WaitingForBootstrapData      4m23s  See proxmox-quickstart-workers-qllcb-ds486, proxmox-quickstart-workers-qllcb-twctl, ...
```

Should the VM template be created using a specific method? i used a standard almalinux cloud init image (Generic Cloud)...

**Comment by mcbenjemaa** [comment]
Does your image have `kubeadm, kubelet, kubectl, containerd` installed?

**Comment by dnviti** [comment]
> Does your image have `kubeadm, kubelet, kubectl, containerd` installed?

nope, if i only need those dependencies i'll cook a new one right away!

**Comment by mcbenjemaa** [comment]
> > Does your image have `kubeadm, kubelet, kubectl, containerd` installed?
> 
> nope, if i only need those dependencies i'll cook a new one right away!

you can add this almalinux to [image-builder ](https://github.com/kubernetes-sigs/image-builder/tree/main/images/capi/packer/proxmox)
otherwise, you can build ubuntu images.

**Comment by mcbenjemaa** [comment]
v0.2.0 is now released

Which means that the issue that you had before, should be fixed.

**Comment by dnviti** [comment]
> v0.2.0 is now released https://github.com/ionos-cloud/cluster-api-provider-proxmox/releases/tag/v0.2.0
> 
> Which means that the issue that you had before, should be fixed.

I also developed this script: https://gitlab.com/dnviti/Bash-Scripts/-/blob/master/capi-proxmox-deps.sh
its purpose it's to prepare an image from scratch in au automated way.
it references another script of mine, to install docker and all its deps.

**Comment by mcbenjemaa** [comment]
join this channel to get support: https://kubernetes.slack.com/archives/C06FC9P0FK7

**Comment by akyriako** [comment]
I am reopening this #513 as I have the same issue since days. Situation is as follows (and I am bit confused where to open the issue, but as long as the error appears in the proxmox provider I do open it here) :

**What steps did you take and what happened:**

✅  When I use **Kubeadm** as ControlPlane provider, the VMs are properly provisioned in Proxmox.
❌  When I use **Kamaji** as ControlPlane provider, I get _"error reconciling VM" err="unable to create new vm: not authorized to access endpoint"_ in **capmox-controller-manager**.

✔️ **Same** VM Template, **same** Proxmox endpoint
✔️  I am using the **same** API Token for both cases
✔️ Priviledge Separation is **unchecked**
✔️ I created an extra API token for `root@pam` (no priviledge separation) just to check with root. **FAILED** as well!
✔️ Yes, the correct credentials are indeed in the `Secret`

**What did you expect to happen:**

Either the VMs to be provisioned or **NOT** provisioned. At least to encounter identical behavior so I can evaluate where the problem is or If I have mis-configured anything. 

**Environment:**

- cluster-api-provider-proxmox:v0.7.2
- cluster-api-controller:v1.10.3
- cluster-api-control-plane-provider-kamaji:v0.15.3

Management Cluster is k3s, Kubernetes version is: v1.32.6+k3s1

**Anything else you would like to add:**

I know it sounds crazy-talk, but yet here we are.
